# Generated by Django 3.0.6 on 2021-07-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210714_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='jobname',
            field=models.CharField(blank=True, default='NA', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.CharField(blank=True, default='NA', max_length=300, null=True),
        ),
    ]
