# Generated by Django 3.0.6 on 2021-07-15 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20210714_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='doi',
            field=models.DateField(blank=True, null=True),
        ),
    ]
