# Generated by Django 3.0.6 on 2021-07-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20210714_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='boss',
        ),
        migrations.AddField(
            model_name='user',
            name='boss_job_name',
            field=models.CharField(blank=True, default='NA', max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='boss_name',
            field=models.CharField(blank=True, default='NA', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='jobname',
            field=models.CharField(blank=True, default='NA', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.CharField(blank=True, default='NA', max_length=600, null=True),
        ),
    ]
