# Generated by Django 3.0.6 on 2021-06-22 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210622_1509'),
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apareance',
            new_name='Relation_e2e',
        ),
        migrations.RenameField(
            model_name='interview',
            old_name='no_children',
            new_name='admon_tiempo_1',
        ),
        migrations.RenameField(
            model_name='relation_e2e',
            old_name='options',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='aca_concordance',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='aca_level',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='apareance',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='aspirations',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='dis_inc',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='dis_travel',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='int_rel',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='interviewer',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='job_afinity',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='other_academy',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='ove_result',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='puntuality',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='recomendation',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='responsability',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='strenghts',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='team_work',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='verbal_com',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='visa',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='w_live',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='weakness',
        ),
        migrations.AddField(
            model_name='interview',
            name='admon_tiempo_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='admon_tiempo_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='admon_tiempo_r',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='comunicacion_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='comunicacion_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='comunicacion_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='comunicacion_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='comunicacion_5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='comunicacion_r',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='enfoque_resultados_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='enfoque_resultados_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='enfoque_resultados_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='enfoque_resultados_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='enfoque_resultados_r',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='evaluated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluated', to='employee.Employee'),
        ),
        migrations.AddField(
            model_name='interview',
            name='evaluator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluator', to='employee.Employee'),
        ),
        migrations.AddField(
            model_name='interview',
            name='general_question',
            field=models.CharField(blank=True, default='0', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='liderazgo_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='liderazgo_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='liderazgo_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='liderazgo_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='liderazgo_5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='liderazgo_r',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='oportunities_areas',
            field=models.CharField(blank=True, default='0', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='pensamiento_estrategico_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='pensamiento_estrategico_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='pensamiento_estrategico_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='pensamiento_estrategico_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='pensamiento_estrategico_r',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interview.Relation_e2e'),
        ),
        migrations.AddField(
            model_name='interview',
            name='resolucion_problemas_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='resolucion_problemas_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='resolucion_problemas_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='resolucion_problemas_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='resolucion_problemas_5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='resolucion_problemas_r',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='result',
            field=models.CharField(blank=True, default='0', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='servicio_cliente_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='servicio_cliente_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='servicio_cliente_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='servicio_cliente_r',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='strengths',
            field=models.CharField(blank=True, default='0', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='trabajo_equipo_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='trabajo_equipo_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='trabajo_equipo_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='trabajo_equipo_r',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='observations',
            field=models.CharField(blank=True, default='0', max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Aca_concordance',
        ),
        migrations.DeleteModel(
            name='Aca_level',
        ),
        migrations.DeleteModel(
            name='Aspirations',
        ),
        migrations.DeleteModel(
            name='Interviewer',
        ),
        migrations.DeleteModel(
            name='Job_afinity',
        ),
        migrations.DeleteModel(
            name='Ove_result',
        ),
        migrations.DeleteModel(
            name='Puntuality',
        ),
        migrations.DeleteModel(
            name='Recomendation',
        ),
        migrations.DeleteModel(
            name='Responsability',
        ),
        migrations.DeleteModel(
            name='Verbal_com',
        ),
    ]
