# Generated by Django 3.0.6 on 2021-07-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='relation',
            field=models.CharField(blank=True, default='No Asignado', max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Relation_e2e',
        ),
    ]
