# Generated by Django 3.0.6 on 2021-07-15 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_auto_20210714_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='dated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
