# Generated by Django 3.0.6 on 2021-06-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_auto_20210625_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='url_signature',
            field=models.CharField(blank=True, default='https://southcentralus1-mediap.svc.ms/transform/thumbnail?provider=spo&inputFormat=png&cs=fFNQTw&docid=https%3A%2F%2Flinkam-my.sharepoint.com%3A443%2F_api%2Fv2.0%2Fdrives%2Fb!tb30pSTWMkSXMivGJmJNbpMzxD32bjdHlSgKAhwQmR7c8pEJKiKZTqNc4Nxxoc94%2Fitems%2F01O6MELQB5DWTTFGN6QVAI6O3VHUBLZYDX%3Fversion%3DPublished&encodeFailures=1&ctag=%22c%3A%7B32A71D3D-BE99-4085-8F3B-753D02BCE077%7D%2C2%22&access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvbGlua2FtLW15LnNoYXJlcG9pbnQuY29tQGVjMDA4MmE5LWU5YzItNGQ2NS1hODFkLTdjM2U2YmRjZjczMyIsImlzcyI6IjAwMDAwMDAzLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMCIsIm5iZiI6IjE2MjQ2NDQwMDAiLCJleHAiOiIxNjI0NjY1NjAwIiwiZW5kcG9pbnR1cmwiOiJldzUrNk50KzM2a1VXVm5kRVhkQmQwRHFYY2FlYzFTeHJOZUUwZURvdzQ4PSIsImVuZHBvaW50dXJsTGVuZ3RoIjoiMTE2IiwiaXNsb29wYmFjayI6IlRydWUiLCJ2ZXIiOiJoYXNoZWRwcm9vZnRva2VuIiwic2l0ZWlkIjoiWVRWbU5HSmtZalV0WkRZeU5DMDBORE15TFRrM016SXRNbUpqTmpJMk5qSTBaRFpsIiwibmFtZWlkIjoiMCMuZnxtZW1iZXJzaGlwfHVybiUzYXNwbyUzYWFub24jZWRjMTIwNjcwYmU3ZTVkYTlkOWQ3Yjg2MzA1ODQ1MjYzNmNjMWVlOGM3NjY4OWEzOWI4MWZlN2U5ODlhYzZkZCIsIm5paSI6Im1pY3Jvc29mdC5zaGFyZXBvaW50IiwiaXN1c2VyIjoidHJ1ZSIsImNhY2hla2V5IjoiMGguZnxtZW1iZXJzaGlwfHVybiUzYXNwbyUzYWFub24jZWRjMTIwNjcwYmU3ZTVkYTlkOWQ3Yjg2MzA1ODQ1MjYzNmNjMWVlOGM3NjY4OWEzOWI4MWZlN2U5ODlhYzZkZCIsInNoYXJpbmdpZCI6ImUzUVVLRS80ZWt1UCtPampnRUdpT1EiLCJ0dCI6IjAiLCJ1c2VQZXJzaXN0ZW50Q29va2llIjoiMiJ9.bGE5SDhxS0s4eDJHMWRDeTIyMFUvZmVlWlZwTEFaTWJvdU8rZmVFNUt4VT0&prooftoken=undefined&srcWidth=&srcHeight=&width=1366&height=581&action=Access', max_length=2000, null=True),
        ),
    ]
