# Generated by Django 3.0.6 on 2021-07-14 19:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise', models.CharField(choices=[('IMEXHS', 'IMEXHS'), ('RIMAB', 'RIMAB'), ('UT', 'UT'), ('COLSUBSIDIO', 'COLSUBSIDIO')], default='RIMAB', max_length=30)),
                ('t_contract', models.CharField(choices=[('FIJO 1 MES', 'FIJO 1 MES'), ('FIJO 3 MESES', 'FIJO 3 MESES'), ('FIJO 4 MESES', 'FIJO 4 MESES'), ('FIJO 6 MESES', 'FIJO 6 MESES'), ('FIJO 7 MESES', 'FIJO 7 MESES')], default='FIJO 3 MESES', max_length=30)),
                ('idate_ctr', models.DateField()),
                ('edate_ctr', models.DateField()),
                ('not_date', models.DateField()),
                ('notified', models.BooleanField()),
                ('renew_ctr', models.BooleanField()),
                ('observation', models.CharField(max_length=300, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 7, 14, 19, 6, 2, 61388, tzinfo=utc))),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
