# Generated by Django 3.0.6 on 2021-07-14 19:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hhrr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 19, 8, 58, 531172, tzinfo=utc)),
        ),
    ]
