# Generated by Django 3.0.6 on 2021-06-22 19:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hhrr', '0002_auto_20200715_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 19, 28, 39, 142110, tzinfo=utc)),
        ),
    ]
