# Generated by Django 3.0.6 on 2021-07-14 21:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hhrr', '0004_auto_20210714_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 21, 46, 45, 685006, tzinfo=utc)),
        ),
    ]
