# Generated by Django 3.0.6 on 2021-06-22 20:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hhrr', '0004_auto_20210622_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 20, 36, 38, 543206, tzinfo=utc)),
        ),
    ]
