# Generated by Django 3.0.6 on 2021-06-25 19:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hhrr', '0005_auto_20210622_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 25, 19, 3, 17, 864599, tzinfo=utc)),
        ),
    ]
