# Generated by Django 3.0.6 on 2021-07-15 00:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hhrr', '0006_auto_20210714_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 0, 18, 22, 35757, tzinfo=utc)),
        ),
    ]
